const products = [
  {
    slug: "the-meridian-watch",
    name: "The Meridian",
    tagline: "A mechanical companion for the long way round.",
    collection: "Horology",
    category: "Watches",
    price: 3200,
    rating: 4.9,
    review_count: 127,
    badge: "Editor's Choice",
    description: "The Meridian is our interpretation of the classic field watch — stripped of pretense, built for a lifetime. A 38mm stainless steel case houses a Swiss Sellita SW200-1 automatic movement, visible through a sapphire exhibition caseback. The dial is a study in restraint: matte black with applied indices, Super-LumiNova, and a date window at 3 o'clock that doesn't shout.",
    story: "We spent eighteen months on the bracelet alone. Three micro-adjustment holes. A clasp that disappears on the wrist. The Meridian doesn't announce itself — it simply becomes part of your daily rhythm, gaining character with every scratch and patina.",
    materials: "316L stainless steel case. Sapphire crystal with AR coating. Sellita SW200-1 automatic movement (38hr power reserve). Italian vegetable-tanned leather strap (optional). 100m water resistance.",
    specs: [
      { label: "Case", value: "38mm × 11.2mm, 316L stainless steel" },
      { label: "Movement", value: "Sellita SW200-1, automatic, 28,800 vph" },
      { label: "Crystal", value: "Domed sapphire, double AR coating" },
      { label: "Water Resistance", value: "100m / 10 ATM" },
      { label: "Strap", value: "20mm quick-release, leather or bracelet" },
      { label: "Warranty", value: "5 years" },
    ],
    images: [
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=1200",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200",
      "https://images.unsplash.com/photo-1547996160-81dfa63595aa?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/meridian",
    reviews: [
      { author: "Marcus T.", date: "March 2024", rating: 5, title: "The only watch I wear", text: "Replaced my entire rotation. The Meridian is honest — no marketing fluff, just exceptional execution." },
      { author: "Elena K.", date: "January 2024", rating: 5, title: "Perfect size", text: "38mm wears larger than expected. The bracelet micro-adjust is a game changer for seasonal wrist changes." },
    ],
  },
  {
    slug: "the-marlow-briefcase",
    name: "The Marlow",
    tagline: "Carries a laptop, a life, and a legacy.",
    collection: "Leather Goods",
    category: "Bags",
    price: 1850,
    rating: 4.8,
    review_count: 89,
    badge: "Bestseller",
    description: "The Marlow is a briefcase for people who don't carry briefcases. Full-grain Tuscan vegetable-tanned leather, hand-stitched in a family workshop outside Florence. Fits a 16\" laptop, documents, and the small rituals of daily work — pen, notebook, charger, keys — each in its own considered pocket.",
    story: "The workshop has made bags for three generations. They don't use machines for the stitching. Each Marlow takes eleven hours. The leather arrives untreated and develops a honey-amber patina that's uniquely yours within months.",
    materials: "Tuscan vegetable-tanned full-grain leather (3.2mm). Solid brass hardware, custom-cast. Cotton twill lining. YKK Excella zipper. Brass feet.",
    specs: [
      { label: "Dimensions", value: "41 × 30 × 10 cm" },
      { label: "Weight", value: "1.8 kg" },
      { label: "Laptop", value: "Fits 16\" MacBook Pro" },
      { label: "Leather", value: "Tuscan veg-tan, 3.2mm" },
      { label: "Hardware", value: "Solid brass, custom" },
      { label: "Warranty", value: "Lifetime" },
    ],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1200",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/marlow",
    reviews: [
      { author: "David R.", date: "February 2024", rating: 5, title: "Ages beautifully", text: "Six months in and the patina is incredible. Strangers ask about it weekly." },
      { author: "Sophie L.", date: "November 2023", rating: 4, title: "Heavy but worth it", text: "It's substantial — 1.8kg empty. But the weight distribution is thoughtful. Shoulders don't ache." },
    ],
  },
  {
    slug: "the-obsidian-hours-sunglasses",
    name: "Obsidian Hours",
    tagline: "See the world on your terms.",
    collection: "Eyewear",
    category: "Sunglasses",
    price: 580,
    rating: 4.7,
    review_count: 203,
    badge: null,
    description: "Japanese titanium frame. Carl Zeiss Vision lenses with triple-layer anti-reflective coating. Adjustable nose pads machined from a single block of beta-titanium. The Obsidian Hours don't sit on your face — they disappear.",
    story: "We worked with a third-generation lens maker in Bavaria and a titanium specialist in Fukui. The result: sunglasses that weigh 18 grams and block 100% UV with zero color distortion. The case is cork — renewable, lightweight, and it smells like the forest it came from.",
    materials: "Beta-titanium frame (18g). Carl Zeiss Vision nylon lenses. Triple AR coating. 100% UV400 protection. Cork case.",
    specs: [
      { label: "Frame", value: "Beta-titanium, 18g" },
      { label: "Lens", value: "Carl Zeiss Vision, nylon" },
      { label: "Coating", value: "Triple-layer anti-reflective" },
      { label: "Protection", value: "UV400, Category 3" },
      { label: "Fit", value: "Adjustable beta-titanium nose pads" },
      { label: "Case", value: "Natural cork" },
    ],
    images: [
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=1200",
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1200",
      "https://images.unsplash.com/photo-1577803645773-f96470509666?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/obsidian-hours",
    reviews: [
      { author: "James P.", date: "April 2024", rating: 5, title: "Invisible comfort", text: "Forgot I was wearing them after 10 minutes. The nose pads are genius — no pressure points." },
      { author: "Aisha M.", date: "January 2024", rating: 5, title: "Best lenses I've owned", text: "Zero distortion at the edges. Colors stay true. Worth every penny." },
    ],
  },
  {
    slug: "the-circle-of-light-ring",
    name: "Circle of Light",
    tagline: "Gold that catches the moment.",
    collection: "Jewellery",
    category: "Rings",
    price: 2400,
    rating: 4.9,
    review_count: 45,
    badge: "New",
    description: "18k recycled yellow gold. A single ethically sourced white diamond (0.15ct, VS1, F-color) set in a bezel that catches light from every angle. The band tapers from 3mm to 1.8mm — substantial where it matters, delicate where it shows.",
    story: "The diamond comes from a Botswana mine that funds schools and hospitals. The gold is 100% recycled from e-waste. The ring is cast and finished by a single goldsmith in London's Hatton Garden. No middlemen. No markup stories.",
    materials: "18k recycled yellow gold. Natural white diamond, 0.15ct, VS1 clarity, F color, Botswana origin. Conflict-free certified.",
    specs: [
      { label: "Metal", value: "18k recycled yellow gold" },
      { label: "Diamond", value: "0.15ct, VS1, F color" },
      { label: "Origin", value: "Botswana, conflict-free" },
      { label: "Band width", value: "3mm → 1.8mm taper" },
      { label: "Sizing", value: "US 4–12, half sizes" },
      { label: "Warranty", value: "Lifetime" },
    ],
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1200",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1200",
      "https://images.unsplash.com/photo-1603974717271-95e0b5c6f4c1?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/circle-of-light",
    reviews: [
      { author: "Claire V.", date: "March 2024", rating: 5, title: "Subtle brilliance", text: "The taper makes it feel substantial but look delicate. Diamond catches light constantly." },
    ],
  },
  {
    slug: "the-everyday-ledger-wallet",
    name: "Everyday Ledger",
    tagline: "The last wallet you'll buy.",
    collection: "Leather Goods",
    category: "Wallets",
    price: 320,
    rating: 4.9,
    review_count: 312,
    badge: "Lifetime Guarantee",
    description: "Eight card slots. Two hidden pockets. A coin purse that doesn't bulge. Bridle leather from Sedgwick's in Walsall — the same tannery that supplies British saddlery. Hand-stitched with Irish linen thread. Edges burnished by hand, not painted.",
    story: "We've replaced three wallets under the lifetime guarantee. Not because they failed — because the owners wore them for 15+ years and the leather simply deserved a refresh. That's the standard.",
    materials: "Sedgwick's bridle leather (3.5mm). Irish linen thread. Solid brass snap. No lining — leather inside and out.",
    specs: [
      { label: "Leather", value: "Sedgwick's bridle, 3.5mm" },
      { label: "Stitching", value: "Irish linen thread, saddle stitch" },
      { label: "Capacity", value: "8 cards, notes, coins" },
      { label: "Dimensions", value: "11.5 × 9.5 × 2 cm" },
      { label: "Hardware", value: "Solid brass" },
      { label: "Warranty", value: "Lifetime (repair or replace)" },
    ],
    images: [
      "https://images.unsplash.com/photo-1620109176813-e91290f6c795?q=80&w=1200",
      "https://images.unsplash.com/photo-1559563458-527698bf5295?q=80&w=1200",
      "https://images.unsplash.com/photo-1584030373282-02d8c3b5f8e2?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/everyday-ledger",
    reviews: [
      { author: "Robert K.", date: "May 2024", rating: 5, title: "Ten years in", text: "Still looks better than new. The patina is unmatched. Lifetime guarantee is real — they refurbished mine free." },
      { author: "Nina S.", date: "December 2023", rating: 5, title: "Perfect size", text: "Fits front pocket. Holds everything. No bulk. The coin purse actually works." },
    ],
  },
  {
    slug: "the-noir-days-belt",
    name: "Noir Days",
    tagline: "Black on black. Forever.",
    collection: "Leather Goods",
    category: "Belts",
    price: 180,
    rating: 4.6,
    review_count: 156,
    badge: null,
    description: "Two layers of Horween Chromexcel, fused without glue. Solid brass buckle with a matte PVD coating that won't chip. Seven holes, 1-inch increments. The Noir Days doesn't crack, stretch, or fade — it only darkens.",
    story: "Chromexcel is stuff-and-stuffed — oils and waxes hot-stuffed into the hide. It's alive. Scratches disappear with a thumb rub. The PVD buckle is the only hardware that matches the leather's commitment to black.",
    materials: "Horween Chromexcel (two layers, 4.5mm total). Solid brass buckle, matte black PVD. Chicago screws (replaceable).",
    specs: [
      { label: "Leather", value: "Horween Chromexcel, double layer" },
      { label: "Thickness", value: "4.5mm" },
      { label: "Buckle", value: "Brass, matte black PVD" },
      { label: "Width", value: "3.5 cm" },
      { label: "Sizes", value: "30–44 inches" },
      { label: "Warranty", value: "5 years" },
    ],
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1200",
      "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/noir-days",
    reviews: [
      { author: "Tomás R.", date: "February 2024", rating: 4, title: "Stiff at first", text: "Needs two weeks to break in. After that, it's the only belt I reach for." },
    ],
  },
  {
    slug: "the-marlow-in-tuscany-keychain",
    name: "Marlow in Tuscany",
    tagline: "A piece of the workshop.",
    collection: "Leather Goods",
    category: "Accessories",
    price: 95,
    rating: 4.8,
    review_count: 67,
    badge: null,
    description: "Cut from the same hide as your Marlow briefcase. A solid brass ring. A snap hook that satisfies. The keychain develops the same honey-amber patina. Small enough to forget. Beautiful enough to remember.",
    story: "Every Marlow briefcase yields enough offcuts for twenty keychains. We number them. When they're gone, they're gone — until the next batch.",
    materials: "Tuscan vegetable-tanned full-grain leather (offcuts). Solid brass hardware.",
    specs: [
      { label: "Leather", value: "Tuscan veg-tan, Marlow offcut" },
      { label: "Hardware", value: "Solid brass ring + snap hook" },
      { label: "Length", value: "12 cm" },
      { label: "Edition", value: "Numbered, batch-limited" },
    ],
    images: [
      "https://images.unsplash.com/photo-1620109176813-e91290f6c795?q=80&w=1200",
      "https://images.unsplash.com/photo-1559563458-527698bf5295?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/marlow-tuscany",
    reviews: [
      { author: "Luca M.", date: "March 2024", rating: 5, title: "Matches my Marlow", text: "Same leather, same patina journey. Number 047 of 120." },
    ],
  },
  {
    slug: "the-gold-standard-bracelet",
    name: "Gold Standard",
    tagline: "Weight you can feel.",
    collection: "Jewellery",
    category: "Bracelets",
    price: 1650,
    rating: 4.7,
    review_count: 34,
    badge: null,
    description: "Solid 18k recycled gold. 18mm wide, 4mm thick. A hidden box clasp that disappears into the design. 48 grams of gold that moves like liquid on the wrist. No plating. No hollow cores. No compromise.",
    story: "Most gold bracelets are hollow. Ours is solid — cast in a single piece, then hand-finished over six hours. The clasp is the hardest part: it must hold securely, open easily, and vanish visually. We went through twelve prototypes.",
    materials: "18k recycled yellow gold. Solid construction. Hidden box clasp with figure-eight safety.",
    specs: [
      { label: "Metal", value: "18k recycled yellow gold" },
      { label: "Weight", value: "~48 grams" },
      { label: "Width", value: "18 mm" },
      { label: "Thickness", value: "4 mm" },
      { label: "Clasp", value: "Hidden box with figure-eight safety" },
      { label: "Warranty", value: "Lifetime" },
    ],
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=1200",
      "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=1200",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/gold-standard",
    reviews: [
      { author: "Viktor A.", date: "January 2024", rating: 5, title: "Substantial", text: "48 grams of solid gold. You feel it. The clasp is engineering art." },
    ],
  },
  {
    slug: "the-signature-scarf",
    name: "The Signature",
    tagline: "Cashmere that remembers.",
    collection: "Textiles",
    category: "Scarves",
    price: 420,
    rating: 4.8,
    review_count: 78,
    badge: null,
    description: "100% Grade A Mongolian cashmere. 200g weight — substantial but not heavy. 70 × 200 cm, woven on vintage looms in Inner Mongolia. Hand-finished fringes. The Signature softens with every wear, molding to your rhythm.",
    story: "The herders comb the goats by hand in spring. The fiber is 14.5 microns — finer than most merino. We pay 3x commodity price. The weavers are a women's cooperative. Every scarf carries a tag with the herder's name.",
    materials: "100% Grade A Mongolian cashmere (14.5 micron). Hand-woven. Hand-finished fringes.",
    specs: [
      { label: "Material", value: "100% Grade A Mongolian cashmere" },
      { label: "Weight", value: "200 g" },
      { label: "Dimensions", value: "70 × 200 cm" },
      { label: "Micron", value: "14.5 µm" },
      { label: "Origin", value: "Inner Mongolia, herder-traced" },
      { label: "Care", value: "Hand wash cold, dry flat" },
    ],
    images: [
      "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?q=80&w=1200",
      "https://images.unsplash.com/photo-1584030373282-02d8c3b5f8e2?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/signature-scarf",
    reviews: [
      { author: "Yuki T.", date: "December 2023", rating: 5, title: "Impossibly soft", text: "After three washes it's somehow softer. The herder tag is a beautiful touch — mine says 'Bat-Erdene'." },
    ],
  },
  {
    slug: "the-horizon-tote",
    name: "Horizon Tote",
    tagline: "Canvas that carries the day.",
    collection: "Leather Goods",
    category: "Bags",
    price: 680,
    rating: 4.6,
    review_count: 112,
    badge: null,
    description: "British Millerain waxed canvas. Bridle leather handles and base. Brass hardware throughout. Laptop sleeve, bottle pockets, key leash. The wax canvas develops a unique patina — creases, marks, stories — and can be re-waxed annually.",
    story: "Millerain has been waxing canvas in Rochdale since 1880. We use their 12oz fabric. The leather is Sedgwick's. The tote is sewn in a London workshop that makes bags for the Royal Household. It's overbuilt on purpose.",
    materials: "British Millerain 12oz waxed canvas. Sedgwick's bridle leather. Solid brass hardware. Cotton drill lining.",
    specs: [
      { label: "Canvas", value: "Millerain 12oz waxed cotton" },
      { label: "Leather", value: "Sedgwick's bridle" },
      { label: "Capacity", value: "22 L, fits 15\" laptop" },
      { label: "Pockets", value: "2 ext, 3 int, 1 laptop, 2 bottle" },
      { label: "Hardware", value: "Solid brass" },
      { label: "Care", value: "Re-wax annually" },
    ],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1200",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/horizon-tote",
    reviews: [
      { author: "Emma W.", date: "March 2024", rating: 5, title: "Daily driver", text: "Commute, gym, weekend trip. The wax canvas handles rain beautifully. Re-waxed once, looks better than new." },
    ],
  },
  {
    slug: "the-architect-pen",
    name: "The Architect",
    tagline: "Writes like it means it.",
    collection: "Writing",
    category: "Pens",
    price: 280,
    rating: 4.9,
    review_count: 56,
    badge: null,
    description: "Titanium body. Schmidt P8126 refill (pressurized — writes upside down, underwater, in -20°C). Machined from a single billet. Weight: 32g. The clip is integrated, not added. No logo. No branding. Just a tool.",
    story: "We wanted a pen that disappears in the hand. Titanium for weight. Pressurized refill for reliability. The machining takes 47 minutes per pen. The clip is part of the body — no rivets, no weak points.",
    materials: "Grade 5 titanium (Ti-6Al-4V). Schmidt P8126 pressurized refill. Ceramic ball. Tungsten carbide tip.",
    specs: [
      { label: "Body", value: "Grade 5 titanium, single billet" },
      { label: "Refill", value: "Schmidt P8126 (pressurized)" },
      { label: "Weight", value: "32 g" },
      { label: "Length", value: "138 mm (capped)" },
      { label: "Diameter", value: "10 mm" },
      { label: "Warranty", value: "Lifetime (body)" },
    ],
    images: [
      "https://images.unsplash.com/photo-1584030373282-02d8c3b5f8e2?q=80&w=1200",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/architect-pen",
    reviews: [
      { author: "Kenji S.", date: "February 2024", rating: 5, title: "Best EDC pen", text: "Writes on receipt paper, wet napkins, frozen car windows. The titanium patina is subtle and beautiful." },
    ],
  },
  {
    slug: "the-compass-keyring",
    name: "Compass Keyring",
    tagline: "True north, always.",
    collection: "Accessories",
    category: "Keyrings",
    price: 120,
    rating: 4.5,
    review_count: 89,
    badge: null,
    description: "Solid brass compass, liquid-damped, 22mm diameter. Stainless steel split ring. The compass actually works — not a novelty. Engraved with VARA coordinates on the back. A reminder that direction is a choice.",
    story: "We sourced the compass movement from a German manufacturer that supplies maritime instruments. The brass case is machined in Birmingham. It's over-engineered for a keyring — exactly the point.",
    materials: "Solid brass case. Liquid-damped compass movement (German). Stainless steel split ring.",
    specs: [
      { label: "Case", value: "Solid brass, 22 mm" },
      { label: "Movement", value: "Liquid-damped, German" },
      { label: "Ring", value: "Stainless steel" },
      { label: "Accuracy", value: "±2°" },
      { label: "Engraving", value: "VARA coordinates" },
    ],
    images: [
      "https://images.unsplash.com/photo-1620109176813-e91290f6c795?q=80&w=1200",
      "https://images.unsplash.com/photo-1559563458-527698bf5295?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/compass-keyring",
    reviews: [
      { author: "Marion K.", date: "January 2024", rating: 4, title: "Actually works", text: "Tested against a Suunto. Accurate. Heavy for a keyring but satisfying." },
    ],
  },
  {
    slug: "the-silence-watch-winder",
    name: "The Silence",
    tagline: "Your automatic, always ready.",
    collection: "Horology",
    category: "Watch Accessories",
    price: 890,
    rating: 4.8,
    review_count: 23,
    badge: null,
    description: "Single-watch winder. Japanese Mabuchi motor — virtually silent (<10dB). Three rotation programs (650, 900, 1200 TPD), bidirectional. Carbon fiber shell, Alcantara interior. Touch-activated. Battery or USB-C.",
    story: "Most winders sound like a fridge. We specified a motor used in medical devices. The carbon shell is made in the same facility that supplies F1 teams. It's a winder that doesn't announce itself.",
    materials: "Carbon fiber shell. Alcantara interior. Japanese Mabuchi motor. USB-C / 4×AA battery.",
    specs: [
      { label: "Motor", value: "Japanese Mabuchi, <10dB" },
      { label: "Programs", value: "650 / 900 / 1200 TPD" },
      { label: "Direction", value: "Clockwise, CCW, bidirectional" },
      { label: "Shell", value: "Carbon fiber" },
      { label: "Interior", value: "Alcantara" },
      { label: "Power", value: "USB-C or 4×AA" },
    ],
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200",
      "https://images.unsplash.com/photo-1547996160-81dfa63595aa?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/silence-winder",
    reviews: [
      { author: "Andre W.", date: "March 2024", rating: 5, title: "Truly silent", text: "On nightstand, zero audible sound. Meridian stays wound perfectly." },
    ],
  },
  {
    slug: "the-field-notebook",
    name: "Field Notebook",
    tagline: "Paper that survives rain.",
    collection: "Writing",
    category: "Notebooks",
    price: 45,
    rating: 4.7,
    review_count: 234,
    badge: "Bestseller",
    description: "Stone paper — no trees, no water, no bleach. Waterproof, tear-resistant, recyclable. 64 pages, dot grid. Sewn binding lays flat. Cover: recycled polyurethane, soft-touch. Pen loop included.",
    story: "Stone paper is calcium carbonate (80%) + HDPE (20%). Made in a solar-powered factory in Taiwan. It feels like premium coated paper but laughs at coffee spills and rain. We've tested it.",
    materials: "Stone paper (CaCO3 + HDPE), 120 gsm. Recycled PU cover. Sewn binding. Elastic closure.",
    specs: [
      { label: "Paper", value: "Stone paper, 120 gsm, dot grid" },
      { label: "Pages", value: "64 (32 sheets)" },
      { label: "Cover", value: "Recycled polyurethane" },
      { label: "Binding", value: "Sewn, lays flat" },
      { label: "Size", value: "13 × 21 cm (A5)" },
      { label: "Features", value: "Waterproof, tear-proof, pen loop" },
    ],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/field-notebook",
    reviews: [
      { author: "Priya D.", date: "April 2024", rating: 5, title: "Survived a monsoon", text: "Left it in a downpour. Pages wet, writing intact. Dried flat. Incredible." },
    ],
  },
  {
    slug: "the-titanium-cardholder",
    name: "Titanium Cardholder",
    tagline: "Six cards. Zero bulk.",
    collection: "Leather Goods",
    category: "Wallets",
    price: 195,
    rating: 4.6,
    review_count: 178,
    badge: null,
    description: "Grade 5 titanium. Holds 6 cards with a thumb-slide mechanism. RFID blocking integrated. Weighs 28g. The titanium anodizes naturally over time — blues, purples, golds — unique to your chemistry.",
    story: "We machined the first prototype from a solid block. The thumb slide went through eighteen iterations. The anodization isn't a coating — it's the titanium oxide layer thickening naturally. No two age alike.",
    materials: "Grade 5 titanium (Ti-6Al-4V). Integrated RFID shield. Stainless steel spring.",
    specs: [
      { label: "Material", value: "Grade 5 titanium" },
      { label: "Capacity", value: "6 cards" },
      { label: "Mechanism", value: "Thumb-slide, stainless spring" },
      { label: "RFID", value: "Integrated shielding" },
      { label: "Weight", value: "28 g" },
      { label: "Dimensions", value: "10 × 6.5 × 1 cm" },
    ],
    images: [
      "https://images.unsplash.com/photo-1620109176813-e91290f6c795?q=80&w=1200",
      "https://images.unsplash.com/photo-1559563458-527698bf5295?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/titanium-cardholder",
    reviews: [
      { author: "Diego M.", date: "February 2024", rating: 5, title: "Anodization is wild", text: "Three months in — deep blue edges, gold center. Looks like a different cardholder every week." },
    ],
  },
  {
    slug: "the-horizon-tote-small",
    name: "Horizon Tote Small",
    tagline: "Same soul. Smaller footprint.",
    collection: "Leather Goods",
    category: "Bags",
    price: 520,
    rating: 4.7,
    review_count: 67,
    badge: null,
    description: "British Millerain 10oz waxed canvas. Sedgwick's bridle leather. 14L capacity — fits 13\" laptop, lunch, layers. The same overbuilt construction as the original, scaled for lighter days.",
    story: "Customers asked for a smaller Horizon. We didn't just shrink it — we re-proportioned. The 10oz canvas is lighter but still Millerain. The leather handles are narrower. It's a different tote, not a mini-me.",
    materials: "Millerain 10oz waxed canvas. Sedgwick's bridle leather. Solid brass. Cotton drill lining.",
    specs: [
      { label: "Canvas", value: "Millerain 10oz waxed cotton" },
      { label: "Leather", value: "Sedgwick's bridle" },
      { label: "Capacity", value: "14 L, fits 13\" laptop" },
      { label: "Pockets", value: "1 ext, 2 int, 1 laptop" },
      { label: "Hardware", value: "Solid brass" },
      { label: "Care", value: "Re-wax annually" },
    ],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/horizon-tote-small",
    reviews: [
      { author: "Sarah J.", date: "March 2024", rating: 5, title: "Perfect commuter", text: "13\" MacBook, water bottle, sweater, notebook. The 10oz canvas is noticeably lighter." },
    ],
  },
  {
    slug: "the-dual-time-ring",
    name: "Dual Time Ring",
    tagline: "Two zones. One finger.",
    collection: "Jewellery",
    category: "Rings",
    price: 1800,
    rating: 4.8,
    review_count: 19,
    badge: "New",
    description: "18k recycled white gold. Two rotating bands — home time and local time. 24-hour markers with Super-LumiNova. The inner band stays fixed; outer rotates with a satisfying detent. 8mm wide, substantial but comfortable.",
    story: "A pilot friend asked for a mechanical world timer he could wear. We built it as a ring. The detent mechanism took four months — 24 precise clicks, zero backlash. The lume glows for eight hours.",
    materials: "18k recycled white gold. Super-LumiNova C3. Stainless steel detent spring.",
    specs: [
      { label: "Metal", value: "18k recycled white gold" },
      { label: "Width", value: "8 mm" },
      { label: "Mechanism", value: "24-click detent, bidirectional" },
      { label: "Lume", value: "Super-LumiNova C3 (8hr glow)" },
      { label: "Sizing", value: "US 6–13, quarter sizes" },
      { label: "Warranty", value: "Lifetime" },
    ],
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1200",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1200",
      "https://images.unsplash.com/photo-1603974717271-95e0b5c6f4c1?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/dual-time-ring",
    reviews: [
      { author: "Captain R.", date: "April 2024", rating: 5, title: "Actually useful", text: "Rotating bezel on a ring — genius. Lume lasts through layover. Detent feel is premium." },
    ],
  },
  {
    slug: "the-meridian-bracelet",
    name: "Meridian Bracelet",
    tagline: "The Meridian, on your wrist.",
    collection: "Horology",
    category: "Watch Accessories",
    price: 420,
    rating: 4.7,
    review_count: 41,
    badge: null,
    description: "316L stainless steel. Micro-adjust clasp with three hidden holes. Tapered links (20mm → 16mm). Quick-release spring bars. Brushed top, polished bevels. Designed for the Meridian — fits any 20mm lug watch.",
    story: "The Meridian deserved a bracelet that matches its standards. The micro-adjust is the same mechanism as the watch clasp. The taper follows the lug curve. It's not an accessory — it's the other half of the watch.",
    materials: "316L stainless steel. Quick-release spring bars. Micro-adjust clasp.",
    specs: [
      { label: "Material", value: "316L stainless steel" },
      { label: "Width", value: "20mm → 16mm taper" },
      { label: "Clasp", value: "Micro-adjust, 3 hidden holes" },
      { label: "Finish", value: "Brushed top, polished bevels" },
      { label: "Spring bars", value: "Quick-release included" },
      { label: "Warranty", value: "5 years" },
    ],
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200",
      "https://images.unsplash.com/photo-1547996160-81dfa63595aa?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/meridian-bracelet",
    reviews: [
      { author: "Meridian owner", date: "February 2024", rating: 5, title: "Changes the watch", text: "The taper makes the 38mm case wear like 40mm. Micro-adjust is clutch for summer/winter." },
    ],
  },
  {
    slug: "the-signature-scarf-large",
    name: "Signature Scarf Large",
    tagline: "Blanket weight. Still cashmere.",
    collection: "Textiles",
    category: "Scarves",
    price: 680,
    rating: 4.9,
    review_count: 34,
    badge: null,
    description: "100% Grade A Mongolian cashmere. 400g — double the weight. 100 × 220 cm. Woven on the same looms, same herders. Can be a scarf, a shawl, a travel blanket. The fringes are 8cm, hand-twisted.",
    story: "The herders comb the winter undercoat. We asked for double weight. They said the goats only give so much. We waited a year for enough fiber. The large Signature is a limited annual run — 200 pieces.",
    materials: "100% Grade A Mongolian cashmere (14.5 micron). 400g. Hand-woven. 8cm hand-twisted fringes.",
    specs: [
      { label: "Material", value: "100% Grade A Mongolian cashmere" },
      { label: "Weight", value: "400 g" },
      { label: "Dimensions", value: "100 × 220 cm" },
      { label: "Micron", value: "14.5 µm" },
      { label: "Fringes", value: "8 cm, hand-twisted" },
      { label: "Edition", value: "200 pieces / year" },
    ],
    images: [
      "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?q=80&w=1200",
      "https://images.unsplash.com/photo-1584030373282-02d8c3b5f8e2?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/signature-scarf-large",
    reviews: [
      { author: "Yuki T.", date: "December 2023", rating: 5, title: "Travel essential", text: "Folded, it's a scarf. Unfolded, it's a blanket on a 14hr flight. The weight grounds you." },
    ],
  },
  {
    slug: "the-architect-pen-titanium",
    name: "Architect Pen Raw",
    tagline: "Unfinished. Unapologetic.",
    collection: "Writing",
    category: "Pens",
    price: 240,
    rating: 4.6,
    review_count: 28,
    badge: null,
    description: "Grade 5 titanium, bead-blasted raw. No anodization. No coating. The surface will mark, patina, and tell your story. Same Schmidt P8126 pressurized refill. Same integrated clip. 32g. For those who prefer honest metal.",
    story: "Some customers asked for the Architect without color. We bead-blast the raw titanium — matte, uniform, tactile. It scratches. It dulls. It becomes yours. The anodized version resists; this one records.",
    materials: "Grade 5 titanium (Ti-6Al-4V), bead-blasted raw. Schmidt P8126 pressurized refill.",
    specs: [
      { label: "Body", value: "Grade 5 titanium, bead-blasted raw" },
      { label: "Refill", value: "Schmidt P8126 (pressurized)" },
      { label: "Weight", value: "32 g" },
      { label: "Length", value: "138 mm (capped)" },
      { label: "Diameter", value: "10 mm" },
      { label: "Warranty", value: "Lifetime (body)" },
    ],
    images: [
      "https://images.unsplash.com/photo-1584030373282-02d8c3b5f8e2?q=80&w=1200",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200",
    ],
    affiliate_url: "https://example.com/architect-pen-raw",
    reviews: [
      { author: "Kenji S.", date: "March 2024", rating: 5, title: "Honest", text: "Six months of pocket carry — the patina is beautiful. Writes through everything." },
    ],
  },
];

const categories = [
  "Watches",
  "Bags",
  "Sunglasses",
  "Rings",
  "Wallets",
  "Belts",
  "Accessories",
  "Bracelets",
  "Scarves",
  "Pens",
  "Keyrings",
  "Watch Accessories",
  "Notebooks",
];

export const mockApi = {
  fetchProducts: async (params = {}) => {
    let result = [...products];
    if (params.featured) result = result.filter(p => p.badge === "Editor's Choice" || p.badge === "Bestseller" || p.badge === "New").slice(0, 4);
    if (params.bestseller) result = result.filter(p => p.badge === "Bestseller").slice(0, 8);
    if (params.category) result = result.filter(p => p.category === params.category);
    return new Promise(r => setTimeout(() => r(result), 100));
  },
  fetchProduct: async (slug) => {
    const product = products.find(p => p.slug === slug);
    return new Promise((resolve, reject) => setTimeout(() => product ? resolve(product) : reject(new Error("Not found")), 100));
  },
  fetchRelated: async (slug) => {
    const product = products.find(p => p.slug === slug);
    if (!product) return [];
    const related = products
      .filter(p => p.slug !== slug && (p.category === product.category || p.collection === product.collection))
      .slice(0, 4);
    return new Promise(r => setTimeout(() => r(related), 100));
  },
  fetchCategories: async () => new Promise(r => setTimeout(() => r(categories), 50)),
  subscribeNewsletter: async (email) => new Promise(r => setTimeout(() => r({ success: true }), 200)),
  submitContact: async (data) => new Promise(r => setTimeout(() => r({ success: true }), 200)),
};

export default mockApi;